### ISSUE TITLE
without STDIO and gem

### ISSUE THREAD

**Issue by and09** [matsumotory/mruby-mrbgem-template#16]
Is possible to add if then else
How reaging on variable NO_STDIO
or how turning on or off on default.gembox

for example my gem will be different when mruby-math exist or not, i can using float or integer or char.

**Comment by matsumotory** [comment]
You can rewrite a `build_config.rb` for your use. ref: https://github.com/mruby/mruby/blob/master/doc/guides/mrbgems.md

**Comment by letarg0** [comment]
Many, many thanks

**Comment by and09** [comment]
Thanks
