### ISSUE TITLE
GitHub Actions instead of TravisCI

### ISSUE THREAD

**Issue by okuramasafumi** [matsumotory/mruby-mrbgem-template#32]
Currently, `.travis.yml` file is included in the generated files.
However, as described in https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing, the new billing plan of Travis is not for those who casually starts developing open source software.
GitHub Actions are widely used as open source communities and it's completely free, so GitHub Actions would be a great alternative to Travis.

My suggestion is that the template will generate `.github/workflows/main.yml` instead of `.travis.yml`.
If possible, it would be best to let users choose CI service to use, just like `bundle gem` command does (see https://bundler.io/v2.2/man/bundle-gem.1.html ).

**Comment by matsumotory** [comment]
@okuramasafumi Very sorry for my late late responses... I overlooked this issue. I agree with your proposal.

**Comment by genya0407** [comment]
It seems that this issue is resolved now 🎉

**Comment by matsumotory** [comment]
@genya0407 Thanks again!
